version: "3.9"

services: 
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8089:8089"
    volumes:
      - /home/qzl/GitProjects/recipe-app-api/app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8089"
      